name: "02. PR Validation"
run-name: "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches: [dev, qa, main]

jobs:
  validate:
    name: Stages 3-8 Validate
    uses: ./.github/workflows/_03-08_validate.yml
    secrets: inherit
