name: Deploy to QA

on:
  push:
    branches: [qa]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: qa
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: qa
      image-tag:   ${{ needs.build.outputs.image-tag }}
    secrets: inherit